### PR TITLE
converted to netstandard2.0

### PR DESCRIPTION
**Pull request by okhosting**

### CODE REVIEW

**Comment by ankane** [comment]
Hi @okhosting, thanks for the PR. Can you add an explanation of the changes? Also, please keep the changeset to a minimum (no `.vs` files, changes to indentation, etc).

**Comment by okhosting** [comment]
Hello @ankane and thanks for this great, very usefull project.

The propossed changes modify the target framework from netstandard2.1 to netstandard2.0 in order to be usable in Net Framework and Xamarin Forms. I had to remove c# 8.0 features and the Range class, but overall test seem to be working fine.

I understand if you feel this as unnecesary to merge, but for myself this will be really usefull. Thank in any case!

**Comment by megafetis** [comment]
Cool! I Wait to confirm PR

**Comment by ankane** [comment]
Big thanks @okhosting! I split into a few different commits to better understand the changes, but everything should be merged now.

**Pull request closed without merging**
