### PR TITLE
 - re-adding support for net6 and net7 to Pgvector.EntityFrameworkCore

### PR DESCRIPTION
**Pull request by RonSijm**
Hey, thanks for making this.

However in 0.2 support for net7 and net8 was broken. So this fixes it again :)

### CODE REVIEW

**Comment by roji** [comment]
This seems to conflate .NET TFMs (net6.0, net8.0) with EF nuget versions - there's no necessary reason that net7.0 users would use EF Core 7.0 (as opposed to e.g. 6.0).

Why not just use an older version o PgVector.EntityFrameworkCore if you need to work with an older version of EF Core?

**Comment by RonSijm** [comment]
> This seems to conflate .NET TFMs (net6.0, net8.0) with EF nuget versions - there's no necessary reason that net7.0 users would use EF Core 7.0 (as opposed to e.g. 6.0).
I suppose you can remove 7.0, my main interest is using net6.0. Though if I was adding net6.0, I'd add net7.0 as well

> Why not just use an older version o PgVector.EntityFrameworkCore if you need to work with an older version of EF Core?

Well I don't know if there are any other changes between 0.1.2 and 0.2.0 - now or in the future - that people would be missing out on if they're hardstuck on v0.1.2

**Comment by roji** [comment]
It's generally not workable for an extension like this to support multiple versions of EF Core, as there are differences - the rename from PostgresUnknownBinaryExpression to PgUnknownBinaryExpression is one such example. If there's some fix in a new version of the extension that's important enough, it can always be backported to an earlier version of the plugin (i.e. 0.1.x) in order to support older versions of EF etc. At least that's how we usually handle extensions/providers.

But @ankane ultimately it's up to you to decide how you want to manage this.

**Comment by ankane** [comment]
Hi @RonSijm, thanks for the PR. As @roji mentioned, EF Core versions can be used across different .NET versions, so I think it's simplest to stay with the current approach (there were also changes to `VectorTypeMapping.cs`, fwiw).

**Pull request closed without merging**
