### PR TITLE
Sync npgsql8 branch with master

### PR DESCRIPTION
**Pull request by roji**
This is a merge of master into the npgsq8 branch, to keep it up to date with recent changes (this will be followed by changing Vector to a readonly struct as per #8).

You may want to rebase it instead to avoid the merge commit - I don't have permission to force-push to that branch, but you can take the sources from this PR if you'd like.

### CODE REVIEW

**Comment by ankane** [comment]
Thanks @roji, just pushed a `npgsql8-v2` branch. Also, I'd only like to make the equality change for 0.2.0, not the others  (https://github.com/pgvector/pgvector-dotnet/issues/8#issuecomment-1609406263).

**Comment by roji** [comment]
@ankane OK. Does that mean you'd accept a PR doing the class/struct change against the `npgsql8-v2` (does that represent 0.2.0)?

**Comment by ankane** [comment]
No, I don't think the class/struct change is needed. If you'd like to submit the equality change against the `npgsql8-v2` branch, we can do that, or just wait until Npgsql 8 is released to make it.

**Comment by roji** [comment]
Oh, I thought you were OK with the readonly struct change.

The current [Vector class](https://github.com/pgvector/pgvector-dotnet/blob/master/src/Pgvector/Vector.cs) is really nothing more than a wrapper around `float[]`; in .NET arrays are reference types, which means that the size of Vector is always exactly one pointer (8 bytes). Having Vector be a class (rather than a struct) means that instances are allocated on the heap, adding GC pressure as these needless instances need to be garbage-collected later. Less importanly, accessing the actual array implies another indirection (both the Vector and array pointers need to be dereferenced; with a struct that's not the case).

Note that this type really does match the criteria on [this page](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct): it's small (always 8 bytes), it already is immutable, and it logically represents a single value (a vector or single array).

To summarize, in the .NET world, making this a readonly struct really is the right thing to do - do you have any particular objection to this, or some reason to prefer it as a class? I'm looping in @stephentoub for his input here as well.

PS An additional improvement we've been discussing is the use of [`ReadOnlyMemory<float>`](https://learn.microsoft.com/en-us/dotnet/api/system.readonlymemory-1?view=net-7.0) to represent vectors instead of `float[]`. ReadOnlyMemory represents an arbitrary continuous region of memory, and has the following advantages:

* It can represent native memory that isn't managed by .NET (e.g. in case a vector is retrieved from some native library via P/Invoke), or even stack-allocated vectors.
* It can represent arbitrary slices of memory in from an existing array. For example, if the user has multiple vectors already laid out sequentially in a single memory region (e.g. loaded as a .NET array directly from disk), that array can be sliced and those slices passed directly to pgvector. With the current array-based design, the user would have to copy the slice out to a new array (additional copy, more GC pressure) just in order to pass it to pgvector.

Note that both `float[]` and `ReadOnlyMemory<float>` can easily be supported, with the Vector class/struct being a discriminated union.

**Pull request closed without merging**
