### PR TITLE
Port to Npgsql 8.0.0-rc.2

### PR DESCRIPTION
**Pull request by roji**
@ankane here's a PR porting pgvector-dotnet to run against 8.0.0-rc.2 versions of Npgsql and the EF provider, which were released today.

We are building some experiments/demos which would greatly benefit from this; so if possible, a prerelease nuget package for this would be greatly appreciated!

### CODE REVIEW

**Comment by bricelam** [comment]
The npgsql8-v2 branch is a bit behind master, but it looks like these changes will still merge cleanly.

**Comment by ankane** [comment]
Hi @roji, thanks for the PR. I don't plan to do more work for Npgsql 8 until the final release, so will revisit this then.

**Comment by roji** [comment]
@ankane are you saying you won't be publishing an 8.0 prerelease package? As I wrote above, we're working on some demos to show off pgvector which depend on 8.0; if no version will be available we'll likely need to switch to another vector database (which would be a shame, PG+pgvector is a great combination for what we have in mind).

**Comment by ankane** [comment]
I typically don't do pre-release versions, but will make an exception. Can you use master as the target branch (for this and any other PRs for 0.2.0-rc.1)? Also, please make sure `VectorTypeInfoResolver.cs` has a trailing newline like the other files.

**Comment by davidfowl** [comment]
We really appreciate it @ankane !!

**Comment by roji** [comment]
@ankane thanks, will do!

**Comment by roji** [comment]
@ankane rebase on top of master.

**Comment by ankane** [comment]
Thanks, will try to get this merged later tonight. A few questions:

1. What's the reason for the `TODO` (making arrays opt-in)?
2. Any other functionality (besides #19) that should be in included in the release candidate? (can also wait a bit if that's better)
3. Unrelated: Is there a way to set Postgres [storage parameters](https://www.postgresql.org/docs/current/sql-createindex.html#SQL-CREATEINDEX-STORAGE-PARAMETERS) for indexes in EF Core? (needed for `lists` with `ivfflat` and `m` and `ef_construction` for `hnsw`)

**Comment by roji** [comment]
> What's the reason for the TODO (making arrays opt-in)?

This is something we also currently have in Npgsql-bundled plugins - there's some last pending work for 8.0. This isn't critical - it's about in general allowing the user to not opt into Npgsql array support, in order to reduce binary size when building with NativeAOT (NativeAOT support is a big feature being delivered for 8.0, and is the primary reason for the plugin API changes in the first place).

Bottom line, this isn't really important - we can very well ship with this TODO; the only effect would be a tiny bit bigger binary for users who don't use PG arrays. 

> Any other functionality (besides https://github.com/pgvector/pgvector-dotnet/pull/19) that should be in included in the release candidate? (can also wait a bit if that's better)

There are some changes I'd recommend around the Vector type:

* Rename from Vector to PgVector to avoid ambiguity with e.g. [.NET Vector](https://learn.microsoft.com/en-us/dotnet/api/system.numerics.vector?view=net-7.0)
* Make it into a readonly struct as we discussed before

I'm happy to do a PR for these as well, if you're OK with them. But otherwise there's nothing I'm aware of.

> Unrelated: Is there a way to set Postgres [storage parameters](https://www.postgresql.org/docs/current/sql-createindex.html#SQL-CREATEINDEX-STORAGE-PARAMETERS) for indexes in EF Core? (needed for lists with ivfflat and m and ef_construction for hnsw)

No, not at the moment - there's support for storage parameters for tables, but not for indexes. If this is important I can add this to the provider 8.0 - let me know.

**Comment by ankane** [comment]
Thanks for the additional context on arrays.

One other change we discussed was equality (if you want to submit a PR - otherwise, I can take a look at it).

Storage parameters for indexes would be great for users (setting `lists` is very important for `ivfflat`, and it'd be nice to be able to set the others for `hnsw` when the defaults don't work well).

**Comment by roji** [comment]
> One other change we discussed was equality (if you want to submit a PR - otherwise, I can take a look at it).

Submitted #22, let's discuss there.

> Storage parameters for indexes would be great for users (setting lists is very important for ivfflat, and it'd be nice to be able to set the others for hnsw when the defaults don't work well).

Opened https://github.com/npgsql/efcore.pg/issues/2899 to track, will give this priority for 8.0.

**Comment by ankane** [comment]
Great, thanks @roji

**Comment by ankane** [comment]
Just published 0.2.0-rc.1 for both Pgvector and Pgvector.EntityFrameworkCore. Let me know if anything else comes up.

**Pull request merged**
