### PR TITLE
Make equality operator work with nulls

### PR DESCRIPTION
**Pull request by roji**
@ankane this is a follow-up to the equality work, discovered during some testing.

### CODE REVIEW

**Comment by ankane** [comment]
Thanks!

**Comment by roji** [comment]
@ankane would it be possible to get rc.2 nuget for this?

**Comment by ankane** [comment]
Yeah, but can we wait a bit to see if any other issues come up?

**Comment by bricelam** [comment]
Everything looks good on our side, all our scenarios are now working again on the latest bits.

**Comment by ankane** [comment]
Great, just pushed 0.2.0-rc.2 for the `Pgvector` package.

**Comment by roji** [comment]
Thanks for the super-quick turnaround @ankane!

**Comment by ankane** [comment]
Updated support for the final 8.0.0 releases in 6f28734cd60e3b4e8ece8cfc13d1a54ed442368d.

**Pull request merged**
